name: Testnet CD

on:
  push:
    tags:
      - '**-beta**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: TESTNET
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.TESTNET_ROLE_ARN }}
        aws-region: ${{ secrets.TESTNET_AWS_REGION }}}

    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci --force # FIXME: PP-648

    - name: Build site
      run: |
        npm run build:testnet

    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors build/ ${{ secrets.TESTNET_S3_BUCKET }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.TESTNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
