name: CD for RIF-Relay-Sample-Dapp

on:
  push:
    branches: [dev, PP-435/dapp-cd]

jobs:
  deploy-develop:
    name: RIF Relay UI - Deploy
    runs-on: ubuntu-latest
    environment: QA

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.QA_AWS_REGION }}

    - name: Setup Node 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm ci

    - name: Build site
      run: |
        npm run build

    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors build/ ${{ secrets.QA_S3_BUCKET }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.QA_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
