name: Testnet CD

on:
  push:
    branches: [dev, PP-575/update-dapp]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: TESTNET

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TESTNET_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TESTNET_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.TESTNET_AWS_REGION }}

    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci

    - name: Build site
      run: |
        npm run build

    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors build/ ${{ secrets.TESTNET_S3_BUCKET }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.TESTNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
